### PR TITLE
Fix parsing and file URIs

### LINKED ISSUE #30: Error while loading FMU
While loading the attached FMU, I get the following error: 

```julia
julia> fmiLoad(fmupath)
[ Info: fmi2Unzip(...): Successfully unzipped 2 files at `C:\Users\RANJAN~1\AppData\Local\Temp\fmifluxjl_naultd\heating`.
┌ Warning: Found enum, but no type definition. Skipping enums.
└ @ FMI C:\Users\Ranjan Anantharaman\.julia\packages\FMI\8Hncl\src\FMI2_md.jl:86
ERROR: ArgumentError: invalid base 10 digit 'f' in "false"
Stacktrace:
  [1] tryparse_internal(#unused#::Type{Int32}, s::String, startpos::Int64, endpos::Int64, base_::Int64, raise::Bool)
    @ Base .\parse.jl:137
  [2] parse(::Type{Int32}, s::String; base::Nothing)
    @ Base .\parse.jl:241
  [3] parse
    @ .\parse.jl:241 [inlined]
  [4] setDatatypeVariables(node::EzXML.Node, md::FMI.fmi2ModelDescription)
    @ FMI C:\Users\Ranjan Anantharaman\.julia\packages\FMI\8Hncl\src\FMI2_md.jl:414
  [5] parseModelVariables(nodes::EzXML.Node, md::FMI.fmi2ModelDescription, derivativeIndices::Vector{Int64})
    @ FMI C:\Users\Ranjan Anantharaman\.julia\packages\FMI\8Hncl\src\FMI2_md.jl:249
  [6] fmi2readModelDescription(pathToModellDescription::String)
    @ FMI C:\Users\Ranjan Anantharaman\.julia\packages\FMI\8Hncl\src\FMI2_md.jl:93
  [7] fmi2Load(pathToFMU::String; unpackPath::Nothing)
    @ FMI C:\Users\Ranjan Anantharaman\.julia\packages\FMI\8Hncl\src\FMI2.jl:335
  [8] #fmiLoad#40
    @ C:\Users\Ranjan Anantharaman\.julia\packages\FMI\8Hncl\src\FMI.jl:193 [inlined]
  [9] fmiLoad(pathToFMU::String)
    @ FMI C:\Users\Ranjan Anantharaman\.julia\packages\FMI\8Hncl\src\FMI.jl:193
 [10] top-level scope
    @ REPL[6]:1
```
[heating.zip](https://github.com/ThummeTo/FMI.jl/files/6993648/heating.zip)

### PR DESCRIPTION
**Pull request by ranjanan**
Fixes #30

### CODE REVIEW

File: src/FMI2.jl [hunk 1]
```diff
@@ -395,7 +395,7 @@ function fmi2Load(pathToFMU::String; unpackPath=nothing)
     end
 
     # make URI ressource location
-    tmpResourceLocation = string("file:/", fmu.path)
+    tmpResourceLocation = string("file:///", fmu.path)
```
Comment (ChrisRackauckas) [inline src/FMI2.jl:398]: isn't that windows specific? Using `joinpath` would probably be safer IIRC. I don't know, @oxinabox is the file guy.

Comment (ranjanan) [reply src/FMI2.jl:398]: Perhaps yeah. I wanted to see if it broke the CI tests.
